### ISSUE TITLE
getting error on 'npm i'

### ISSUE THREAD

**Issue by mikesmayer** [proyecto26/nativescript-ionic-template#1]
nice work on this seed --but I'm getting an error when I run 'npm i'

any thoughts?

> nativescript-ionic-template@0.0.0 postinstall /Users/mike/Code/nativescript-ionic-template
> node symlink.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/mike/Code/nativescript-ionic-template/symlink.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativescript-ionic-template@0.0.0 postinstall: `node symlink.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-ionic-template@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jdnichollsc** [comment]
What's your OS? Windows?

**Comment by mikesmayer** [comment]
mac

**Comment by jdnichollsc** [comment]
@mikesmayer fixed! it was an issue with the gitignore of https://github.com/TeamMaestro/angular-native-seed/, please check again 👍
