### ISSUE TITLE
/src/fonts/Ionicons.ttf

### ISSUE THREAD

**Issue by qudansdl** [proyecto26/nativescript-ionic-template#2]
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module not found: Error: Can't resolve './fonts/ionicons.ttf?v=3.0.0-alpha.3' in '/home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src'
resolve './fonts/ionicons.ttf?v=3.0.0-alpha.3' in '/home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src'
  using description file: /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/package.json (relative path: ./src)
    using description file: /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/package.json (relative path: ./src/fonts/ionicons.ttf)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf.js doesn't exist
      as directory
        /home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf doesn't exist
[/home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf]
[/home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf.ts]
[/home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf.js]
[/home/poh/projects/Brix/sources/BrixShop/sources/trunk/frontend/src/fonts/ionicons.ttf]
 @ ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss 6:462842-462889 6:544996-545043
 @ ./src/styles.scss
 @ multi ./src/styles.scss

**Comment by jdnichollsc** [comment]
😆
